# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c72a0325616e0295b9210ee2860c197c"
name = "auiz-app"
handle = "auiz-app"
application_url = "https://detroit-rwanda-pamela-fighter.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "cocho-123.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://detroit-rwanda-pamela-fighter.trycloudflare.com/auth/callback",
  "https://detroit-rwanda-pamela-fighter.trycloudflare.com/auth/shopify/callback",
  "https://detroit-rwanda-pamela-fighter.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[app_proxy]
url = "https://detroit-rwanda-pamela-fighter.trycloudflare.com/quizzes"
subpath = "proxy"
prefix = "apps"

[pos]
embedded = false
